In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# ! pip install scikit-learn


In [2]:
df =pd.read_csv(r"C:\Users\Asus\OneDrive\Desktop\Data Science 16\sitp_16\machine learning\Cleaned_Data_Used_Bike.csv")

In [3]:
df 

bike_name  price  city  kms_driven  owner  age  power  brand
0             1      1     1           1      1    1      1      1
1             2      2     2           2      1    2      2      2
2             3      3     2           3      1    3      3      3
3             4      4     3           4      1    2      4      1
4             5      5     3           5      1    1      5      4
...         ...    ...   ...         ...    ...  ...    ...    ...
7319        471     43     2        3720      1    3      5      6
7320         27      1     3         523      1   10     13      7
7321        242    473   185        3721      1    2     25     15
7322        115    744     8        1666      1    2     26      7
7323         90      5     8        3722      1    6     13      7

[7324 rows x 8 columns]

In [4]:
x =df.drop('price',axis=1)
y =df[['price']]

In [5]:
y   ## dep 


price
0         1
1         2
2         3
3         4
4         5
...     ...
7319     43
7320      1
7321    473
7322    744
7323      5

[7324 rows x 1 columns]

In [6]:
x  ### undep 

bike_name  city  kms_driven  owner  age  power  brand
0             1     1           1      1    1      1      1
1             2     2           2      1    2      2      2
2             3     2           3      1    3      3      3
3             4     3           4      1    2      4      1
4             5     3           5      1    1      5      4
...         ...   ...         ...    ...  ...    ...    ...
7319        471     2        3720      1    3      5      6
7320         27     3         523      1   10     13      7
7321        242   185        3721      1    2     25     15
7322        115     8        1666      1    2     26      7
7323         90     8        3722      1    6     13      7

[7324 rows x 7 columns]

In [7]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test=train_test_split(x , y , random_state=42 , test_size=0.2)


In [8]:
x_train

bike_name  city  kms_driven  owner  age  power  brand
4506        421     4        2238      1   16      1      1
2758        133    11        1328      1    4      8      2
640         147   103         341      1    4      1      6
5824         74     3        2964      1    5      5      4
6703        336    19         186      1    6      8      2
...         ...   ...         ...    ...  ...    ...    ...
5191         13    36         600      1   10     10      7
5226        133     8        1843      1    6      8      2
5390        176     6        2724      1    6      5      7
860          63     4         438      1    3      5      4
7270         70     2         186      1   11      9      5

[5859 rows x 7 columns]

In [9]:
y_train

price
4506    118
2758    102
640     126
5824     28
6703    115
...     ...
5191   1007
5226    328
5390    243
860      28
7270      5

[5859 rows x 1 columns]

In [10]:
x_train.shape, y_train.shape , x_test.shape, y_test.shape 

((5859, 7), (5859, 1), (1465, 7), (1465, 1))

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lr =LinearRegression()

In [13]:
lr.fit(x_train, y_train)

LinearRegression()

In [14]:
lr.score(x_train, y_train)

0.02559177745050112

In [15]:
lr.score(x_test, y_test)    

0.012267381452817805

In [16]:
pred =lr.predict(x_test)

In [17]:
pred 

array([[154.98676928],
       [187.11296885],
       [236.97676553],
       ...,
       [201.43992685],
       [191.3030958 ],
       [170.487214  ]], shape=(1465, 1))

In [18]:
y_test

price
3795    840
1562    528
4480     84
3718     57
5887     22
...     ...
4417    265
527     102
3309    684
5077    328
565      99

[1465 rows x 1 columns]

In [19]:
from sklearn.svm import SVR 
svg=SVR()
svg.fit(x_train, y_train)

c:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [20]:
svg.score(x_train, y_train)

-0.14801327799744013

In [21]:
svg.score(x_test, y_test)

-0.12729029928323143

In [22]:
from sklearn.svm import SVC
svc_obj=SVC()
from sklearn.datasets import load_iris
x , y =load_iris(return_X_y=True)
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test=train_test_split(x , y , random_state=42 , test_size=0.2)
svc_obj.fit(x_train, y_train)
svc_obj.score(x_train, y_train)
svc_obj.score(x_test, y_test)

1.0

In [23]:
svc_obj.predict(x_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [24]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [25]:
##knn#
from sklearn.neighbors import KNeighborsClassifier
knn_obj=KNeighborsClassifier()
knn_obj.fit(x_train, y_train)
knn_obj.score(x_train, y_train)
knn_obj.score(x_test, y_test)

1.0

In [26]:
knn_obj.score(x_train, y_train)

0.9666666666666667

In [27]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor()

In [28]:
knn.fit(x_train, y_train)

KNeighborsRegressor()

In [29]:
knn.score(x_train, y_train)

0.9635404578542041

In [30]:
knn.score(x_test, y_test)

0.9885532591414944

In [31]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
dtr.fit(x_train, y_train)



DecisionTreeRegressor()

In [32]:
dtr.score(x_train, y_train)

1.0

In [33]:
dtr.score(x_test, y_test)

1.0

In [34]:
dtr.predict(x_test)

array([1., 0., 2., 1., 1., 0., 1., 2., 1., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0.])

In [35]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [36]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.datasets import load_breast_cancer
x , y =load_breast_cancer(return_X_y=True)
from sklearn.model_selection import train_test_split
x_train , x_test, y_train, y_test=train_test_split(x, y , random_state=42, test_size=2)
gnb = GaussianNB()
gnb.fit(x_train, y_train)
print("this is train score ]:-", gnb.score(x_train, y_train))
print("this is test score ]:-", gnb.score(x_test, y_test))


this is train score ]:- 0.9417989417989417
this is test score ]:- 1.0


In [37]:
from sklearn.datasets import load_iris
x , y =load_iris(return_X_y=True)

from sklearn.cluster import KMeans
Kmeans = KMeans(n_clusters=3)
Kmeans.fit(x)
labels = Kmeans.predict(x)
print(labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 2 2 2 1 2 2 2 2
 2 2 1 1 2 2 2 2 1 2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 1 2 2 2 1 2
 2 1]


In [38]:
import pandas as pd
pd.read_csv(r"https://raw.githubusercontent.com/upflairs-pvt-ltd/3rd_july_datascience/master/farmer_guider/farmer.csv")

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]